import ResultState from './context/ResultState'
import './globals.css'
import type { Metadata } from 'next'
import {Jost} from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const jost = Jost({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <ResultState>
          {children}
        </ResultState>
      </body>
    </html>
  )
}
